image: 'fpoli/prusti-base'

stages:
  - test

variables:
  RUST_BACKTRACE: 1
  RUST_TEST_THREADS: 1

cache:
  paths:
    - /usr/local/cargo/

test:
  stage: test
  script:
    - lscpu
    - apt-get purge viper -y
    - apt-get autoremove -y
    - wget -q -O - https://pmserver.inf.ethz.ch/viper/debs/xenial/key.asc | apt-key add -
    - echo "deb http://pmserver.inf.ethz.ch/viper/debs/xenial /" | tee /etc/apt/sources.list.d/viper.list
    - apt-get update
    - apt-get dist-upgrade -y
    - apt-get install viper -y
    - silicon --version || true
    - /"$Z3_EXE" -version
    - java -version
    - rustc --version
    - cargo --version
    - cargo build --all
    - cargo test --all --verbose -- --nocapture
    - ./bin/prusti prusti/tests/verify/pass/no-annotations/assert-true.rs
