image: 'ubuntu:16.04'

stages:
- test

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  Z3_PATH: /usr/local/bin/z3
  APT_CACHE_DIR: $CI_PROJECT_DIR/apt-cache

cache:
  paths:
  - target/
  - $CARGO_HOME/
  - $APT_CACHE_DIR/

test:
  stage: test
  before_script:
  - apt-get update -y -qq && apt-get install -y -qq build-essential curl wget unzip
  - bash <(curl https://sh.rustup.rs -sSf) -y --default-toolchain "$(cat rust-toolchain)"
  - curl -L http://pmserver.inf.ethz.ch/viper/debs/xenial/key.asc | apt-key add -
  - echo 'deb http://pmserver.inf.ethz.ch/viper/debs/xenial /' | tee /etc/apt/sources.list.d/viper.list
  - apt-get update -y -qq && apt-get install -y -qq viper default-jdk
  - wget -q 'https://github.com/Z3Prover/z3/releases/download/z3-4.8.1/z3-4.8.1.016872a5e0f6-x64-ubuntu-16.04.zip' -O z3.zip
  - unzip z3.zip
  - cp z3-*/bin/z3 "$Z3_PATH"
  - chmod +x "$Z3_PATH"
  - rm -r z3.zip z3-*
  script:
  - silicon --version || true
  - /"$Z3_PATH" -version
  - java -version
  - rustc -version
  - cargo -version
  - cargo build --all
  - cargo test --verbose -- --nocapture
  - ./docker/prusti prusti/tests/verify/pass/no-annotations/assert-true.rs
