image: 'rust:latest'

stages:
- test

variables:
  CARGO_HOME: $CI_PROJECT_DIR/cargo
  APT_CACHE_DIR: $CI_PROJECT_DIR/apt
  Z3_PATH: /usr/local/bin/z3

cache:
  paths:
  - target/
  - $CARGO_HOME
  - $APT_CACHE_DIR


test:
  stage: test
  before_script:
  - curl -L http://pmserver.inf.ethz.ch/viper/debs/xenial/key.asc | apt-key add -
  - echo 'deb http://pmserver.inf.ethz.ch/viper/debs/xenial /' | tee /etc/apt/sources.list.d/viper.list
  - apt-get update -yq
  - apt-get install -o dir::cache::archives="$APT_CACHE_DIR" -y viper openjdk-11-jdk
  - wget https://github.com/Z3Prover/z3/releases/download/z3-4.8.1/z3-4.8.1.016872a5e0f6-x64-ubuntu-16.04.zip -O z3.zip
  - unzip z3.zip
  - cp z3-*/bin/z3 "$Z3_PATH"
  - rm -r z3.zip z3-*
  - rustup default "$(cat rust-toolchain)"
  script:
  - silicon -version
  - ./"$Z3_PATH" -version
  - java -version
  - rustc -version
  - cargo -version
  - cargo build -all
  - cargo test -verbose --nocapture
  - ./docker/prusti prusti/tests/verify/pass/no-annotations/assert-true.rs
