image: 'fpoli/prusti-deps:latest'

stages:
- test

variables:
  RUST_BACKTRACE: 1
  RUST_TEST_THREADS: 1

cache:
  paths:
  - target/
  - $CARGO_HOME

test:
  stage: test
  script:
  - silicon --version || true
  - /"$Z3_PATH" -version
  - java -version
  - rustc --version
  - cargo --version
  - cargo build --all
  - cargo test --all --verbose -- --nocapture
  - ./docker/prusti prusti/tests/verify/pass/no-annotations/assert-true.rs
