image: 'fpoli/prusti-base'

stages:
  - test

variables:
  RUST_BACKTRACE: 1
  RUST_TEST_THREADS: 1

cache:
  paths:
    - /usr/local/cargo/

test:
  stage: test
  script:
    - lscpu
    - silicon --version || true
    - /"$Z3_EXE" -version
    - java -version
    - rustc --version
    - cargo --version
    - cargo build --all
    - cargo test --all --verbose -- --nocapture
    - ./docker/prusti prusti/tests/verify/pass/no-annotations/assert-true.rs
