language: rust
cache: cargo
dist: trusty

os:
  - linux

rust:
  - stable
  - beta
  - nightly

jdk:
  - oraclejdk8

env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - LD_LIBRARY_PATH=$JAVA_HOME/jre/lib/amd64/server
    - ASM_JAR=/usr/share/java/asm4.jar

before_script:
  - export RUST_BACKTRACE=1
  - echo $JAVA_HOME
  - echo $LD_LIBRARY_PATH
  - sudo apt-get install viper

script:
  - cargo build
  - cargo test
