language: rust
cache: cargo
dist: xenial

os:
  - linux

rust:
  - stable
  - beta
  - nightly

jdk:
  - oraclejdk8

env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - LD_LIBRARY_PATH=$JAVA_HOME/jre/lib/amd64/server
    - ASM_JAR=$HOME/asm.jar
    - RUST_BACKTRACE=1

before_install:
  - wget -c http://pmserver.inf.ethz.ch/viper/debs/xenial/key.asc -O /tmp/key.asc
  - sudo apt-key add /tmp/key.asc
  - echo 'deb http://pmserver.inf.ethz.ch/viper/debs/xenial /' | sudo tee /etc/apt/sources.list.d/viper.list
  - sudo apt-get update

install:
  - wget "http://central.maven.org/maven2/asm/asm/3.3.1/asm-3.3.1.jar" -O "$ASM_JAR"
  - sudo apt-get install viper

script:
  - cargo test

after_success:
  - |
      if [[ "$TRAVIS_OS_NAME" == "linux" && "$TRAVIS_PULL_REQUEST" = "false" && "$TRAVIS_BRANCH" == "master" ]]; then
        cargo rustdoc -- --no-defaults --passes collapse-docs --passes unindent-comments --passes strip-priv-imports &&
        echo "<meta http-equiv=refresh content=0;url=viper/index.html>" > target/doc/index.html &&
        git clone https://github.com/davisp/ghp-import.git &&
        ./ghp-import/ghp_import.py -n -p -f -m "Documentation upload" -r https://"$GH_TOKEN"@github.com/"$TRAVIS_REPO_SLUG.git" target/doc &&
        echo "Uploaded documentation"
      fi
