language: rust
cache: cargo
dist: trusty
sudo: false

rust:
  - stable
  - beta
  - nightly

jdk:
  - oraclejdk8

env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - LD_LIBRARY_PATH=$JAVA_HOME/jre/lib/amd64/server
    - ASM_JAR=$HOME/asm.jar
    - RUST_BACKTRACE=1

install:
  - wget "http://central.maven.org/maven2/asm/asm/3.3.1/asm-3.3.1.jar" -O "$ASM_JAR"
  - rustup install nightly
  - cargo +nightly install rustfmt-nightly || true
  - cargo +nightly install clippy || true

script:
  - cargo +nightly fmt -- --write-mode=diff
  - cargo build -vv
  - cargo test --verbose -- --nocapture
  - cargo +nightly clippy
  - cd testcrate
  - cargo +nightly fmt -- --write-mode=diff
  - cargo build -vv
  - cargo test --verbose -- --nocapture
  - cargo +nightly clippy
