language: rust
cache: cargo
dist: trusty
sudo: false

rust:
  - nightly

before_install:
  # Download our version of rustc.
  - echo "Getting rustc." &&
    wget -O rustc-stage2.tar.gz http://pmserver.inf.ethz.ch/viper/debs/trusty/rust/rustc-stage2.tar.gz &&
    tar -xf rustc-stage2.tar.gz &&
    rm -f rustc-stage2.tar.gz &&
    mkdir -p .cache &&
    mv stage2 .cache/rustc-stage2

install:
  - rustup toolchain link stage2 .cache/rustc-stage2/
  - rustup default stage2

script:
  - cargo build
  - cargo test --verbose -- --nocapture
