language: rust
cache: cargo
dist: trusty
sudo: false

rust:
  - stable
  - beta
  - nightly

jdk:
  - oraclejdk8

env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - LD_LIBRARY_PATH=$JAVA_HOME/jre/lib/amd64/server
    - RUST_BACKTRACE=1

install:
  - if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      cargo install rustfmt-nightly clippy --force;
    fi

script:
  - cargo build -vv
  - cargo test --verbose -- --nocapture
  - if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      cargo clean &&
      cargo fmt -- --write-mode=diff &&
      cargo clippy;
    fi
  - cd testcrate
  - cargo build -vv
  - cargo test --verbose -- --nocapture
  - if [[ "$TRAVIS_RUST_VERSION" == "nightly" ]]; then
      cargo clean &&
      cargo clippy;
    fi
