language: rust
cache: cargo
sudo: false
dist: trusty

os:
  - linux

rust:
  - stable
  - beta
  - nightly

jdk:
  - oraclejdk8

env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - LD_LIBRARY_PATH=$JAVA_HOME/jre/lib/amd64/server

before_script:
  - export RUST_BACKTRACE=1
  - echo $JAVA_HOME
  - echo $LD_LIBRARY_PATH
  - mkdir tmp
  - wget "http://central.maven.org/maven2/asm/asm/3.3.1/asm-3.3.1.jar" -O tmp/asm.jar

script:
  - cargo test
  - cd systest && cargo test
