language: rust
cache: cargo
dist: trusty
sudo: false

rust:
  - nightly
  - nightly-2018-06-27

matrix:
  allow_failures:
  - rust: nightly

install:
  - cargo install --force clippy rustfmt-nightly

script:
  - cargo build
  - cargo test --verbose -- --nocapture
  - cargo clean
  - cargo fmt -- --write-mode=diff || true
  - cargo clippy || true
