language: rust
cache: cargo
dist: trusty
os:
  - linux

sudo: false

rust:
  - nightly

before_script:
  - ( ( cargo install clippy && export CLIPPY=true ) || export CLIPPY=false );
  - export PATH=$PATH:~/.cargo/bin
  - cargo install --force rustfmt-nightly

script:
  - cargo fmt -- --write-mode=diff
  - cargo build
  - cargo test
  - |
      if [[ $CLIPPY ]]; then
        cargo clippy
      fi
