language: rust
dist: trusty
sudo: true

rust:
  - nightly

jdk:
  - oraclejdk8

cache:
  cargo: true
  directories:
  # Cache the Z3 build
  - .cache

env:
  global:
    # Required to call the JVM
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - LD_LIBRARY_PATH=$JAVA_HOME/jre/lib/amd64/server
    # Required to run viper on Trusty
    - Z3_PATH=/usr/bin/z3

before_install:
  # Add Viper's PPA
  - wget -q -O - http://pmserver.inf.ethz.ch/viper/debs/xenial/key.asc | sudo apt-key add -
  - echo 'deb http://pmserver.inf.ethz.ch/viper/debs/xenial /' | sudo tee /etc/apt/sources.list.d/viper.list
  - travis_retry sudo apt-get update
  # Download and compile Z3 with a known-to-work version
  - if [ ! -d .cache/z3 ]; then
      echo "Building Z3 from scratch";
      wget -O z3.zip https://github.com/Z3Prover/z3/archive/3865c453827506fc5c9d6c6c7c3d66d17030f158.zip;
      unzip z3.zip;
      rm z3.zip;
      mv z3-3865c453827506fc5c9d6c6c7c3d66d17030f158 tmp-z3;
      cd tmp-z3;
      ./configure;
      cd build;
      make -j 2;
      cd ../..;
      mv tmp-z3 .cache/z3;
    else
      echo "Using cached Z3";
      ls .cache/z3;
    fi

install:
  - travis_retry sudo apt-get install viper
  - ( cd .cache/z3/build; sudo make install )
  - cargo install --force clippy rustfmt-nightly

script:
  - cargo fmt -- --write-mode=diff
  - cargo build
  - cargo test
  - cargo clean
  - cargo clippy
