language: rust
cache: cargo
sudo: false
dist: trusty

os:
  - linux

rust:
  - stable
  - beta
  - nightly

jdk:
  - oraclejdk8

env:
  global:
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle
    - LD_LIBRARY_PATH=$JAVA_HOME/jre/lib/amd64/server
    - ASM_JAR=/usr/share/java/asm4.jar
    - RUST_BACKTRACE=1

script:
  - cargo test
  - cargo test --manifest-path testcrate/Cargo.toml
