[workspace]
members = [
    "prusti",
    "prusti-contracts",
    "prusti-contracts-impl",
    "prusti-contracts-internal",
    "prusti-specs",
    "prusti-env-utils",
    "prusti-common",
    "prusti-interface",
    "prusti-viper",
    "prusti-server",
    "prusti-launch",
    "viper",
    "viper-sys",
    "jni-gen",
	"jni-gen/systest",
]

exclude = [
    "prusti-contracts-test",
]
