[package]
name = "prusti-interface"
version = "0.1.0"
authors = ["Federico Poli <federpoli@gmail.com>"]
description = "Interface between prusti and prusti-viper"
license = "MPL-2.0"
readme = "README.md"

[dependencies]
log = "0.3"
lazy_static = "1.0"

[dev-dependencies]
env_logger = "0.4.3"

[badges]
travis-ci = { repository = "viperproject/prusti-interface", branch = "master" }
