[package]
authors = ["Federico Poli"]
description = "Low-level wrappers around Viper"
name = "viper-sys"
readme = "README.md"
version = "0.1.0"
build = "build.rs"

[dependencies]
error-chain = "0.11.0"
jni = { path = "../../jni-rs", features = ["backtrace", "invocation"] }

[build-dependencies]
jni-gen = { path = "../jni-gen" }
error-chain = "0.11.0"
env_logger = "0.4.3"
