[package]
authors = ["Federico Poli <federpoli@gmail.com>"]
description = "Low-level wrappers around Viper"
name = "viper-sys"
readme = "README.md"
version = "0.1.0"
build = "build.rs"

[build-dependencies]
jni-gen = { git = "https://github.com/viperproject/jni-gen.git" }
error-chain = "0.11.0"
env_logger = "0.4.3"

[dependencies]
error-chain = "0.11.0"
jni = { version = "0.9.0", features = ["backtrace", "invocation"] }

[badges]
travis-ci = { repository = "viperproject/viper-sys", branch = "master" }

[profile.dev]
codegen-units = 8

[profile.release]
codegen-units = 8

[profile.test]
codegen-units = 8

[profile.bench]
codegen-units = 8

[profile.doc]
codegen-units = 8
