[workspace]
members = [
	"viper",
	"viper-sys",
	"prusti-contracts",
	"prusti",
	"prusti-viper",
	"jni-gen",
	"jni-gen/systest",
	"prusti-interface",
	"prusti-filter",
]
exclude = ["prusti-internal"]
