[package]
authors = ["Federico Poli"]
description = "Low-level wrappers around Viper"
name = "viper-sys"
readme = "README.md"
version = "0.1.0"

[dependencies]
log = "0.3"
error-chain = "0.11.0"
jni = { path = "../../jni-rs", features = ["backtrace", "invocation"] }

[dev-dependencies]
env_logger = "0.4.3"
