[package]
authors = ["Federico Poli"]
description = "Expose the raw Viper API"
name = "viper-sys"
readme = "README.md"
version = "0.1.0"
links = "jvm"
build = "build.rs"

[dependencies]
jni-sys = "0.3.0"
jni = { path = "../../jni-rs" } # "0.7.1"
