[package]
name = "viper-sys"
version = "0.1.0"
description = "Low-level interface to Viper"
authors = ["Federico Poli <federpoli@gmail.com>"]
license = "MPL-2.0"
readme = "README.md"
build = "build.rs"

[build-dependencies]
jni-gen = { git = "https://github.com/viperproject/jni-gen.git" }
error-chain = "0.11.0"
env_logger = "0.4.3"

[dependencies]
error-chain = "0.11.0"
env_logger = "0.4.3"
jni = { version = "0.9.0", features = ["backtrace", "invocation"] }
log = "0.3"

[badges]
travis-ci = { repository = "viperproject/viper-sys", branch = "master" }
