[package]
authors = ["Federico Poli <federpoli@gmail.com>"]
description = "High-level Viper API"
name = "viper"
readme = "README.md"
version = "0.1.0"

[dependencies]
log = "0.3"
error-chain = "0.11.0"
viper-sys = { git = "https://github.com/viperproject/viper-sys.git" }
jni = { version = "0.9.0", features = ["backtrace", "invocation"] }
uuid = { version = "0.4", features = ["v4"] }

[dev-dependencies]
lazy_static = "1.0"
env_logger = "0.4.3"
bencher = "0.1.5"

[badges]
travis-ci = { repository = "viperproject/viper", branch = "master" }

[[bench]]
name = "bench_program"
harness = false

[profile.dev]
codegen-units = 8

[profile.release]
codegen-units = 8

[profile.test]
codegen-units = 8

[profile.bench]
codegen-units = 8

[profile.doc]
codegen-units = 8
