[package]
authors = ["Federico Poli <federpoli@gmail.com>"]
description = "Low-level wrappers around Viper"
name = "viper-sys"
readme = "README.md"
version = "0.1.0"
build = "build.rs"

[dependencies]
error-chain = "0.11.0"
jni = { git = "https://github.com/prevoty/jni-rs.git", branch = "invocation_api", features = ["backtrace", "invocation"] }

[build-dependencies]
jni-gen = { git = "https://github.com/viperproject/jni-gen.git" }
error-chain = "0.11.0"
env_logger = "0.4.3"
