[package]
authors = ["Federico Poli <federpoli@gmail.com>"]
description = "Generate wrappers around Java and Scala code using the `jni` crate."
name = "jni-gen"
readme = "README.md"
version = "0.1.0"

[dependencies]
log = "0.3"
error-chain = "0.11.0"
jni = { version = "0.9.0", features = ["backtrace", "invocation"] }

[dev-dependencies]
env_logger = "0.4.3"

[badges]
travis-ci = { repository = "viperproject/jni-gen", branch = "master" }
