[package]
authors = ["Federico Poli <federpoli@gmail.com>"]
description = "High-level Viper API"
name = "viper"
readme = "README.md"
version = "0.1.0"

[dependencies]
log = "0.3"
error-chain = "0.11.0"
viper-sys = { git = "https://github.com/viperproject/viper-sys.git" }
jni = { version = "0.9.0", features = ["backtrace", "invocation"] }

[dev-dependencies]
lazy_static = "1.0"
env_logger = "0.4.3"

[badges]
travis-ci = { repository = "viperproject/viper", branch = "master" }
