[package]
authors = ["Federico Poli"]
description = "Expose the raw Viper API"
name = "viper-sys"
readme = "README.md"
version = "0.1.0"
links = "jvm"
build = "build.rs"

[dependencies]
log = "0.3"
error-chain = "0.11.0"
jni = { path = "../../jni-rs" } # "0.7.1"

[dev-dependencies]
env_logger = "0.4.3"
