[workspace]
members = ["viper", "viper-sys", "prusti_contracts", "prusti", "prusti-viper", "jni-gen", "jni-gen/systest", "prusti-utils", "prusti-interface"]

[patch."https://github.com/viperproject/jni-gen.git"]
jni-gen = { path = "jni-gen" }

[patch."https://github.com/viperproject/viper-sys.git"]
viper-sys = { path = "viper-sys" }

[patch."https://github.com/viperproject/viper.git"]
viper = { path = "viper" }

[patch."https://github.com/viperproject/prusti-viper.git"]
prusti-viper = { path = "prusti-viper" }

[patch."https://github.com/viperproject/prusti_contracts.git"]
prusti_contracts = { path = "prusti_contracts" }

[patch."https://github.com/viperproject/prusti-utils.git"]
prusti-utils = { path = "prusti-utils" }

[patch."https://github.com/viperproject/prusti-interface.git"]
prusti-interface = { path = "prusti-interface" }
