[package]
name = "prusti"
version = "0.1.0"
authors = ["Vytautas Astrauskas <vastrauskas@gmail.com>"]

[lib]
name = "prusti"
plugin = true

[badges]
travis-ci = { repository = "viperproject/prusti", branch = "master" }

[dependencies]
log = "0.3"
env_logger = "0.3"
