[package]
authors = ["Federico Poli"]
description = "Generate JNI wrappers given a list of JARs and a list of classes to be wrapped."
name = "jni-gen"
readme = "README.md"
version = "0.1.0"

[dependencies]
log = "0.3"
error-chain = "0.11.0"
jni = { path = "../../jni-rs", features = ["backtrace", "invocation"] }

[dev-dependencies]
env_logger = "0.4.3"
