[package]
authors = ["Federico Poli <federpoli@gmail.com>"]
description = "High-level wrappers around Viper"
name = "viper"
readme = "README.md"
version = "0.1.0"

[dependencies]
error-chain = "0.11.0"
viper-sys = { git = "https://github.com/viperproject/viper-sys.git" }
