[package]
name = "jni-gen"
version = "0.1.0"
description = "Generator of Rust bindings to Java classes"
authors = ["Federico Poli <federpoli@gmail.com>"]
license = "MPL-2.0"
readme = "README.md"

[dependencies]
log = "0.3"
error-chain = "0.11.0"
jni = { version = "0.9.3", features = ["backtrace", "invocation"] }

[dev-dependencies]
env_logger = "0.4.3"

[badges]
travis-ci = { repository = "viperproject/jni-gen", branch = "master" }
