[package]
name = "prusti_contracts"
version = "0.1.0"
authors = ["Vytautas Astrauskas <vastrauskas@gmail.com>"]

[badges]
travis-ci = { repository = "viperproject/prusti_contracts", branch = "master" }

[dependencies]
