[package]
name = "prusti-common"
version = "0.1.0"
authors = ["Julian Dunskus <julian.dunskus@gmail.com>"]

[dependencies]
log = { version = "0.4", features = ["release_max_level_info"] }
viper = { path = "../viper" }
config = "0.9"
serde = "1.0"
serde_derive = "1.0"
lazy_static = "1.0"
uuid = { version = "0.7", features = ["v4"] }
regex = "1.0.5"
