[package]
name = "prusti-common"
version = "0.1.0"
authors = ["Julian Dunskus <julian.dunskus@gmail.com>"]

[dependencies]
log = { version = "0.4", features = ["release_max_level_info"] }
walkdir = "2"
