[package]
name = "prusti-contracts-impl"
version = "0.1.0"
authors = ["Vytautas Astrauskas <vastrauskas@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
prusti-specs = { path = "../prusti-specs" }
proc-macro-hack = "0.5"
quote = "1.0"